### PR TITLE
221 - Reverts reset logic to fix group-list and block bugs

### LINKED ISSUE #221: Revert multiple form reset logic to fix `group-list` and `block` bug
We essentially need to revert the `set` and `setIn` logic that this PR introduced:
https://github.com/tinacms/tina-graphql-gateway/pull/192

Temporary fix for https://github.com/tinacms/tina-graphql-gateway/issues/212 until we have a more permanent solution.

### PR DESCRIPTION
**Pull request by Enigmatical**
Keeps most of the `reset` logic in place except for the use of `setIn(...)` over `set(...)`.  This allows for a single `reset`, but not multiple.  This is a known bug, but it solves much larger issues with `group-list` and `block` that depend on `set(...)`.

Closes #221

### CODE REVIEW

File: apps/demo/pages/_app.tsx [hunk 1]
```diff
@@ -43,12 +43,12 @@ function MyApp({ Component, pageProps }: AppProps) {
...
-  clientId: 'some-id',
-  organizationId: 'gctc',
-  branch: 'main',
-})
+const client = new LocalClient()
+// const client = new Client({
+//   clientId: 'some-id',
+//   organizationId: 'gctc',
+//   branch: 'main',
+// })
```
Comment (Enigmatical) [inline apps/demo/pages/_app.tsx:51]: I decided to commit this.  I can take it back out, but I feel like we would probably prefer to test locally with `demo`.

**Review by jeffsee55 — APPROVED** [review]
